server:
  port: 9001 #服务端口号
  servlet:
    context-path: /consumer
spring:
  application:
    name: serverconsumer  #微服务名称，对外暴漏的微服务名称，十分重要

logging:
  config: /data/project/server-consumer/config/log4j2.xml

eureka:
  client: #将客户端注册到 eureka 服务列表内
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_INSTANCE_LIST}  #这个地址是 7001注册中心在 application.yml 中暴露出来额注册地址 （单机版）
  instance:
    instance-id: serverconsumer-9001 #自定义服务名称信息
    prefer-ip-address: true  #显示访问路径的 ip 地址
    #hostname: ${HOSTNAME}
########################################## spring cloud 使用 Spring Boot actuator 监控完善信息###################################
# Spring Boot 2.50对 actuator 监控屏蔽了大多数的节点，只暴露了 heath 节点，本段配置（*）就是为了开启所有的节点
management:
  endpoints:
    web:
      exposure:
        include: "*"   # * 在yaml 文件属于关键字，所以需要加引号
info:
  app.name: serverconsumer
  company.name: com.mcmin
