server:
  port: 8761  #该 Module 的端口号
  servlet:
    context-path: /eurekaserver
eureka:
  instance:
    prefer-ip-address: false
    hostname: ${EUREKA_INSTANCE_HOST_NAME} #eureka服务端的实例名称，
  client:
    register-with-eureka: false #false表示不向注册中心注册自己。
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: ${EUREKA_INSTANCE_LIST} #单机版服务注册中心
  server:
    enable-self-preservation: true #关闭安全模式

logging:
  config: /data/project/eureka-server/config/log4j2.xml
